[[module.imports]]
  path = "github.com/feathericons/feather"
  disable = false
  [[module.imports.mounts]]
    source = "."
    target = "assets/feather"

[[module.imports]]
  path = "github.com/FortAwesome/Font-Awesome"
  disable = false
  [[module.imports.mounts]]
    source = "."
    target = "assets/FortAwesome/Font-Awesome"

[[module.imports]]
  path = "github.com/twbs/icons"
  disable = false
  [[module.imports.mounts]]
    source = "."
    target = "assets/twbs/icons"